### ISSUE TITLE
Add a printchar

### ISSUE THREAD

**Issue by alexburroughs** [alexburroughs/JessieScript#11]
Be able to print a number corresponding ascii value to the screen, maybe a certain amount of characters at a time
ex: 
printchar 5
prints the ascii of the first 5 values on the stack

**Comment by vedi0boy** [comment]
If we do have a number of items to print, we should also add an argument for pop, so we can do printchar 5 and then pop 5. Might be tough, but i think the next step is arrays.

Thanks,
Nate

________________________________

**Comment by alexburroughs** [comment]
donezo
