### ISSUE TITLE
Add the ability to add comments to code

### ISSUE THREAD

**Issue by vedi0boy** [alexburroughs/JessieScript#2]
I want to be able to make comments. Prefix suggestions:
```
~
--
//
# 
!
```

**Comment by alexburroughs** [comment]
This might be difficult because to the way it reads the code,it should be line by line but is not. I will add them but they'll be a bit weird

**Comment by vedi0boy** [comment]
ah, I understand.

maybe start line by line, then read each line char by char, it will be easier to refactor that way
